import { useState } from "react";
import {
  ArrowRight,
  Check,
  Download,
  LoaderCircle,
  Wallet,
  CheckCircle2,
  RefreshCw,
} from "lucide-react";
import { money, reviewOf, post, exportProposal } from "../lib.js";

export function Review({ project, onApproved, onError }) {
  const [review, setReview] = useState(() => reviewOf(project));
  const [confirmed, setConfirmed] = useState(false),
    [busy, setBusy] = useState(false);
  const total = review.milestones.reduce((a, m) => a + Number(m.percent), 0);
  const updateMilestone = (i, key, value) =>
    setReview((r) => ({
      ...r,
      milestones: r.milestones.map((m, j) =>
        j === i ? { ...m, [key]: value } : m,
      ),
    }));
  async function approve(e) {
    e.preventDefault();
    setBusy(true);
    try {
      onApproved(await post(`/projects/${project.id}/approve`, review));
    } catch (error) {
      onError(error.message);
    } finally {
      setBusy(false);
    }
  }
  return (
    <form className="review" onSubmit={approve}>
      <section className="panel">
        <div className="section-header">
          <div>
            <h2>Review your proposal</h2>
            <p className="muted">
              Generated by {project.model}{" "}
              {project.source === "groq" ? "through Groq" : "on your machine"}.
              Edit anything before approval.
            </p>
          </div>
          <span className="project-total">
            {money(project.totalCents)}
            <small>{project.client}</small>
          </span>
        </div>
        <label htmlFor="proposal-title">Project title</label>
        <input
          id="proposal-title"
          required
          maxLength={120}
          value={review.title}
          onChange={(e) => setReview({ ...review, title: e.target.value })}
        />
        <label htmlFor="summary">Scope summary</label>
        <textarea
          id="summary"
          className="short-textarea"
          required
          maxLength={1000}
          value={review.summary}
          onChange={(e) => setReview({ ...review, summary: e.target.value })}
        />
        <div className="review-milestones">
          {review.milestones.map((m, i) => (
            <article className="review-milestone" key={i}>
              <div className="milestone-heading">
                <span className="number">{i + 1}</span>
                <label className="sr-only" htmlFor={`title-${i}`}>
                  Milestone {i + 1} title
                </label>
                <input
                  id={`title-${i}`}
                  required
                  maxLength={120}
                  value={m.title}
                  onChange={(e) => updateMilestone(i, "title", e.target.value)}
                />
                <label className="percentage">
                  <input
                    aria-label={`Milestone ${i + 1} percentage`}
                    type="number"
                    min="1"
                    max="98"
                    required
                    value={m.percent}
                    onChange={(e) =>
                      updateMilestone(i, "percent", Number(e.target.value))
                    }
                  />
                  <span>%</span>
                </label>
              </div>
              <label htmlFor={`description-${i}`}>Deliverables</label>
              <textarea
                id={`description-${i}`}
                className="short-textarea"
                maxLength={600}
                required
                value={m.description}
                onChange={(e) =>
                  updateMilestone(i, "description", e.target.value)
                }
              />
              <label htmlFor={`criteria-${i}`}>
                Acceptance criteria · one per line
              </label>
              <textarea
                id={`criteria-${i}`}
                className="short-textarea"
                required
                value={m.criteria.join("\n")}
                onChange={(e) =>
                  updateMilestone(i, "criteria", e.target.value.split("\n"))
                }
              />
            </article>
          ))}
        </div>
        <p className={total === 100 ? "muted" : "validation"}>
          Milestone allocation: {total}% of the budget
          {total !== 100
            ? " — must total 100%."
            : ". Final cents are reconciled on the last milestone."}
        </p>
        <div className="scope-notes">
          {[
            ["assumptions", "Assumptions"],
            ["exclusions", "Out of scope"],
          ].map(([key, label]) => (
            <div key={key}>
              <label htmlFor={key}>{label} · one per line</label>
              <textarea
                id={key}
                required
                className="short-textarea"
                value={review[key].join("\n")}
                onChange={(e) =>
                  setReview({ ...review, [key]: e.target.value.split("\n") })
                }
              />
            </div>
          ))}
        </div>
        <div className="review-footer">
          <label className="checkbox-label">
            <input
              type="checkbox"
              checked={confirmed}
              onChange={(e) => setConfirmed(e.target.checked)}
            />
            I reviewed the scope and payment allocation. Approval locks this
            proposal.
          </label>
          <button
            className="button primary"
            disabled={!confirmed || total !== 100 || busy}
          >
            {busy ? (
              <LoaderCircle size={18} className="spin" />
            ) : (
              <Check size={18} />
            )}
            Approve scope
            <ArrowRight size={18} />
          </button>
        </div>
      </section>
    </form>
  );
}

export function Payments({
  project,
  status,
  onUpdated,
  onError,
  onConnections,
  returnInfo,
  onDismissReturn,
}) {
  const [selected, setSelected] = useState(returnInfo?.index ?? 0),
    [accepted, setAccepted] = useState(false),
    [busy, setBusy] = useState(false);
  const milestone = project.milestones[selected];
  const paid = project.milestones
    .filter((m) => m.payment)
    .reduce((a, m) => a + m.amountCents, 0);
  const returned =
    returnInfo &&
    !returnInfo.cancelled &&
    returnInfo.index === selected &&
    returnInfo.token;
  async function checkout() {
    setBusy(true);
    try {
      const order = await post(
        `/projects/${project.id}/milestones/${selected}/order`,
        { accepted },
      );
      window.location.assign(order.approvalUrl);
    } catch (error) {
      onError(error.message);
      setBusy(false);
    }
  }
  async function capture() {
    setBusy(true);
    try {
      const updated = await post(
        `/projects/${project.id}/milestones/${selected}/capture`,
        { orderId: returned ? returnInfo.token : milestone.order?.id },
      );
      onUpdated(updated);
      onDismissReturn();
    } catch (error) {
      onError(error.message);
    } finally {
      setBusy(false);
    }
  }
  return (
    <>
      <section className="panel payment-summary">
        <div>
          <span className="muted">Approved proposal · {project.client}</span>
          <h2>{project.title}</h2>
          <p className="muted">{project.summary}</p>
        </div>
        <div className="project-total">
          {money(project.totalCents)}
          <small>{money(paid)} paid in sandbox</small>
          <button
            className="text-button"
            onClick={() => exportProposal(project)}
          >
            <Download size={16} />
            Export proposal
          </button>
        </div>
      </section>
      {returnInfo?.cancelled && (
        <div className="notice" role="status">
          Checkout was cancelled. No payment has been marked as paid.
        </div>
      )}
      <div className="payment-layout">
        <section className="panel milestone-list">
          <h2>Project milestones</h2>
          <p className="muted">Each milestone has its own PayPal payment.</p>
          {project.milestones.map((m, i) => (
            <button
              key={i}
              className={`milestone-select ${selected === i ? "selected" : ""}`}
              onClick={() => {
                setSelected(i);
                setAccepted(false);
              }}
            >
              <span className="number">
                {m.payment ? <Check size={16} /> : i + 1}
              </span>
              <div>
                <strong>{m.title}</strong>
                <span>
                  {m.payment ? "Paid in sandbox" : "Awaiting payment"} ·{" "}
                  {m.percent}%
                </span>
              </div>
              <strong>{money(m.amountCents)}</strong>
            </button>
          ))}
          <div className="promise">
            <ShieldNote />
          </div>
        </section>
        <section className="panel checkout-panel">
          <div className="section-header">
            <h2>
              {milestone.payment
                ? "Payment received"
                : returned
                  ? "Finish your sandbox payment"
                  : "Buyer checkout"}
            </h2>
            <Wallet size={24} />
          </div>
          <p className="muted">Local sandbox demo · milestone {selected + 1}</p>
          <h3>{milestone.title}</h3>
          <p>{milestone.description}</p>
          <h4>Acceptance criteria</h4>
          <ul className="criteria-list">
            {milestone.criteria.map((c, i) => (
              <li key={i}>
                <CheckCircle2 size={18} />
                <span>{c}</span>
              </li>
            ))}
          </ul>
          <div className="payment-amount">
            <span>
              Milestone payment <small>USD · PayPal sandbox</small>
            </span>
            <strong>{money(milestone.amountCents)}</strong>
          </div>
          {milestone.payment ? (
            <div className="receipt">
              <CheckCircle2 size={24} />
              <div>
                <strong>Verified PayPal capture</strong>
                <p>
                  Capture ID: <code>{milestone.payment.captureId}</code>
                </p>
                <p>{new Date(milestone.payment.paidAt).toLocaleString()}</p>
              </div>
            </div>
          ) : returned ? (
            <>
              <p className="muted">
                You returned from PayPal. We’ll verify approval and capture this
                order on the server.
              </p>
              <button
                className="button primary full"
                disabled={busy}
                onClick={capture}
              >
                {busy ? (
                  <LoaderCircle className="spin" size={18} />
                ) : (
                  <Check size={18} />
                )}
                Complete sandbox payment
              </button>
            </>
          ) : (
            <>
              <label className="checkbox-label">
                <input
                  type="checkbox"
                  checked={accepted}
                  onChange={(e) => setAccepted(e.target.checked)}
                />
                As the sandbox buyer, I accept this milestone’s criteria and
                payment amount.
              </label>
              <button
                className="button paypal-button full"
                disabled={!accepted || busy || !status?.paypal.configured}
                onClick={checkout}
              >
                {busy ? (
                  <LoaderCircle className="spin" size={18} />
                ) : (
                  <Wallet size={18} />
                )}
                Pay {money(milestone.amountCents)} with PayPal
              </button>
              {!status?.paypal.configured && (
                <p className="setup-hint">
                  Sandbox credentials are required.{" "}
                  <button className="text-button" onClick={onConnections}>
                    Configure connections
                  </button>
                </p>
              )}
              {milestone.order && (
                <button
                  className="text-button reconcile"
                  disabled={busy}
                  onClick={capture}
                >
                  <RefreshCw size={16} />
                  Check payment status
                </button>
              )}
            </>
          )}
          <p className="payment-footnote">
            Sandbox only. No real money moves. Direct payment to the configured
            sandbox merchant; no escrow.
          </p>
        </section>
      </div>
    </>
  );
}
function ShieldNote() {
  return (
    <p className="muted">
      Scope is locked after approval. A payment is recorded only after PayPal
      confirms the capture.
    </p>
  );
}

export function SavedProjects({ projects, onOpen, onNew }) {
  return (
    <section className="panel saved-projects">
      <div className="section-header">
        <h2>
          Saved projects <span className="muted">({projects.length})</span>
        </h2>
        <button className="button primary" onClick={onNew}>
          New proposal
          <ArrowRight size={16} />
        </button>
      </div>
      {projects.length === 0 ? (
        <div className="empty-state">
          <h3>A fresh start.</h3>
          <p className="muted">
            Your generated proposals will appear here, ready to review and
            collect payment.
          </p>
        </div>
      ) : (
        projects.map((p) => (
          <button className="project-row" key={p.id} onClick={() => onOpen(p)}>
            <div>
              <strong>{p.title}</strong>
              <span>
                {p.client} · {new Date(p.createdAt).toLocaleDateString()} ·{" "}
                {p.state === "draft" ? "Needs review" : "Approved"}
              </span>
            </div>
            <strong>{money(p.totalCents)}</strong>
            <ArrowRight size={18} />
          </button>
        ))
      )}
    </section>
  );
}
